import React from "react";
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from "@react-pdf/renderer";
import type { AnalysisResult, ClaimAnalysis, InspectionReport, DamageFinding } from "./analyze";

const styles = StyleSheet.create({
  page: {
    fontFamily: "Helvetica",
    fontSize: 11,
    paddingTop: 48,
    paddingBottom: 60,
    paddingHorizontal: 48,
    color: "#1a1a1a",
  },
  coverTitle: {
    fontSize: 26,
    fontFamily: "Helvetica-Bold",
    marginBottom: 8,
    color: "#1e3a5f",
  },
  coverSubtitle: {
    fontSize: 14,
    color: "#4a4a4a",
    marginBottom: 32,
  },
  coverMeta: {
    fontSize: 10,
    color: "#666",
    marginBottom: 4,
  },
  coverDisclaimer: {
    marginTop: 40,
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 4,
    fontSize: 10,
    color: "#555",
    lineHeight: 1.6,
  },
  sectionHeader: {
    fontSize: 14,
    fontFamily: "Helvetica-Bold",
    marginTop: 24,
    marginBottom: 8,
    color: "#1e3a5f",
    borderBottomWidth: 1,
    borderBottomColor: "#dce3ec",
    paddingBottom: 4,
  },
  claimBox: {
    marginBottom: 20,
    padding: 12,
    backgroundColor: "#f9fafb",
    borderRadius: 4,
    borderLeftWidth: 4,
    borderLeftColor: "#aaa",
  },
  claimBoxValid: { borderLeftColor: "#dc2626" },
  claimBoxInvalid: { borderLeftColor: "#16a34a" },
  claimBoxPartial: { borderLeftColor: "#d97706" },
  claimBoxInsufficient: { borderLeftColor: "#6b7280" },
  claimTitle: {
    fontSize: 12,
    fontFamily: "Helvetica-Bold",
    marginBottom: 6,
  },
  verdictBadge: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 3,
    alignSelf: "flex-start",
    marginBottom: 8,
    color: "#fff",
    backgroundColor: "#6b7280",
  },
  verdictValid: { backgroundColor: "#dc2626" },
  verdictInvalid: { backgroundColor: "#16a34a" },
  verdictPartial: { backgroundColor: "#d97706" },
  verdictInsufficient: { backgroundColor: "#6b7280" },
  label: {
    fontSize: 9,
    fontFamily: "Helvetica-Bold",
    color: "#555",
    marginTop: 6,
    marginBottom: 2,
    textTransform: "uppercase",
  },
  body: {
    fontSize: 10,
    lineHeight: 1.5,
    color: "#333",
  },
  amountRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  amountLabel: { fontSize: 10, color: "#555" },
  amountValue: { fontSize: 10, fontFamily: "Helvetica-Bold" },
  summaryBox: {
    marginTop: 16,
    padding: 14,
    backgroundColor: "#eef2f7",
    borderRadius: 4,
  },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  totalLabel: { fontSize: 11, color: "#333" },
  totalValue: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  totalHighlight: { color: "#16a34a" },
  nextStepItem: {
    fontSize: 10,
    lineHeight: 1.5,
    marginBottom: 4,
    color: "#333",
  },
  footer: {
    position: "absolute",
    bottom: 24,
    left: 48,
    right: 48,
    fontSize: 8,
    color: "#999",
    textAlign: "center",
    borderTopWidth: 1,
    borderTopColor: "#eee",
    paddingTop: 6,
  },
  photoRef: {
    fontSize: 9,
    color: "#555",
    marginBottom: 2,
    paddingLeft: 8,
  },
});

function verdictLabel(verdict: ClaimAnalysis["verdict"]): string {
  switch (verdict) {
    case "likely_valid": return "LIKELY VALID — Landlord favoured";
    case "likely_invalid": return "LIKELY INVALID — Dispute this";
    case "partially_valid": return "PARTIALLY VALID — Negotiate";
    case "insufficient_evidence": return "INSUFFICIENT EVIDENCE";
  }
}

function claimBoxStyle(verdict: ClaimAnalysis["verdict"]) {
  switch (verdict) {
    case "likely_valid": return [styles.claimBox, styles.claimBoxValid];
    case "likely_invalid": return [styles.claimBox, styles.claimBoxInvalid];
    case "partially_valid": return [styles.claimBox, styles.claimBoxPartial];
    case "insufficient_evidence": return [styles.claimBox, styles.claimBoxInsufficient];
  }
}

function verdictBadgeStyle(verdict: ClaimAnalysis["verdict"]) {
  switch (verdict) {
    case "likely_valid": return [styles.verdictBadge, styles.verdictValid];
    case "likely_invalid": return [styles.verdictBadge, styles.verdictInvalid];
    case "partially_valid": return [styles.verdictBadge, styles.verdictPartial];
    case "insufficient_evidence": return [styles.verdictBadge, styles.verdictInsufficient];
  }
}

function formatCAD(amount: number | null): string {
  if (amount === null) return "N/A";
  return `$${amount.toFixed(2)}`;
}

const DISCLAIMER =
  "This document is not legal advice. It is generated by an AI system for informational purposes only. " +
  "For legal guidance, consult a licensed paralegal or visit Steps to Justice at stepstojustice.ca. " +
  "You may also contact the Landlord and Tenant Board at 1-888-332-3234.";

interface RebuttalDocumentProps {
  result: AnalysisResult;
  generatedAt: string;
}

export function RebuttalDocument({ result, generatedAt }: RebuttalDocumentProps) {
  return (
    <Document title="DepositDefender — Tenant Rebuttal">
      {/* Cover Page */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.coverTitle}>DepositDefender</Text>
        <Text style={styles.coverSubtitle}>Tenant Security Deposit Dispute Rebuttal</Text>
        <Text style={styles.coverMeta}>Generated: {generatedAt}</Text>
        <Text style={styles.coverMeta}>Jurisdiction: Ontario, Canada (RTA / LTB)</Text>

        <View style={styles.summaryBox}>
          <Text style={{ fontSize: 12, fontFamily: "Helvetica-Bold", marginBottom: 8 }}>
            Summary
          </Text>
          <Text style={styles.body}>{result.overall_summary}</Text>
          <View style={{ marginTop: 12 }}>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total amount claimed by landlord:</Text>
              <Text style={styles.totalValue}>{formatCAD(result.total_claimed_cad)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total amount disputable:</Text>
              <Text style={[styles.totalValue, styles.totalHighlight]}>
                {formatCAD(result.total_disputable_cad)}
              </Text>
            </View>
          </View>
        </View>

        <Text style={styles.coverDisclaimer}>{DISCLAIMER}</Text>

        <Text style={styles.footer}>
          DepositDefender — Not legal advice — stepstojustice.ca — LTB: 1-888-332-3234
        </Text>
      </Page>

      {/* Claims Pages */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.sectionHeader}>Claim-by-Claim Analysis</Text>

        {result.claims.map((claim, i) => (
          <View key={i} style={claimBoxStyle(claim.verdict)} wrap={false}>
            <Text style={styles.claimTitle}>
              {i + 1}. {claim.claim}
            </Text>

            <Text style={verdictBadgeStyle(claim.verdict)}>
              {verdictLabel(claim.verdict)}
            </Text>

            <View style={styles.amountRow}>
              <View>
                <Text style={styles.label}>Claimed</Text>
                <Text style={styles.amountValue}>{formatCAD(claim.claimed_amount_cad)}</Text>
              </View>
              <View>
                <Text style={styles.label}>Suggested dispute</Text>
                <Text style={[styles.amountValue, styles.totalHighlight]}>
                  {formatCAD(claim.suggested_dispute_amount_cad)}
                </Text>
              </View>
            </View>

            <Text style={styles.label}>Reasoning</Text>
            <Text style={styles.body}>{claim.reasoning}</Text>

            <Text style={styles.label}>Wear & Tear Assessment</Text>
            <Text style={styles.body}>{claim.wear_and_tear_assessment}</Text>

            {claim.photo_references.length > 0 && (
              <>
                <Text style={styles.label}>Photo Evidence</Text>
                {claim.photo_references.map((ref, j) => (
                  <Text key={j} style={styles.photoRef}>• {ref}</Text>
                ))}
              </>
            )}
          </View>
        ))}

        <Text style={styles.footer}>
          DepositDefender — Not legal advice — stepstojustice.ca — LTB: 1-888-332-3234
        </Text>
      </Page>

      {/* Next Steps Page */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.sectionHeader}>Recommended Next Steps</Text>

        {result.recommended_next_steps.map((step, i) => (
          <Text key={i} style={styles.nextStepItem}>
            {i + 1}. {step}
          </Text>
        ))}

        <View style={[styles.summaryBox, { marginTop: 24 }]}>
          <Text style={{ fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 6 }}>
            Final Totals
          </Text>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total claimed by landlord:</Text>
            <Text style={styles.totalValue}>{formatCAD(result.total_claimed_cad)}</Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Total disputable amount:</Text>
            <Text style={[styles.totalValue, styles.totalHighlight]}>
              {formatCAD(result.total_disputable_cad)}
            </Text>
          </View>
        </View>

        <View style={[styles.coverDisclaimer, { marginTop: 24 }]}>
          <Text>{DISCLAIMER}</Text>
        </View>

        <Text style={styles.footer}>
          DepositDefender — Not legal advice — stepstojustice.ca — LTB: 1-888-332-3234
        </Text>
      </Page>
    </Document>
  );
}

// ── Landlord Inspection Report ───────────────────────────────────────────────

const inspectionStyles = StyleSheet.create({
  severityNone: { backgroundColor: "#6b7280" },
  severityCosmetic: { backgroundColor: "#3b82f6" },
  severityModerate: { backgroundColor: "#d97706" },
  severitySignificant: { backgroundColor: "#dc2626" },
  wearBadge: { backgroundColor: "#16a34a" },
  chargeableBadge: { backgroundColor: "#dc2626" },
  conditionExcellent: { color: "#16a34a" },
  conditionGood: { color: "#2563eb" },
  conditionFair: { color: "#d97706" },
  conditionPoor: { color: "#dc2626" },
});

function severityLabel(severity: DamageFinding["severity"]): string {
  switch (severity) {
    case "none": return "NO DAMAGE";
    case "cosmetic": return "COSMETIC";
    case "moderate": return "MODERATE";
    case "significant": return "SIGNIFICANT";
  }
}

function severityBadgeStyle(severity: DamageFinding["severity"]) {
  switch (severity) {
    case "none": return [styles.verdictBadge, inspectionStyles.severityNone];
    case "cosmetic": return [styles.verdictBadge, inspectionStyles.severityCosmetic];
    case "moderate": return [styles.verdictBadge, inspectionStyles.severityModerate];
    case "significant": return [styles.verdictBadge, inspectionStyles.severitySignificant];
  }
}

function conditionStyle(condition: InspectionReport["overall_condition"]) {
  switch (condition) {
    case "excellent": return inspectionStyles.conditionExcellent;
    case "good": return inspectionStyles.conditionGood;
    case "fair": return inspectionStyles.conditionFair;
    case "poor": return inspectionStyles.conditionPoor;
  }
}

function conditionLabel(condition: InspectionReport["overall_condition"]): string {
  return condition.charAt(0).toUpperCase() + condition.slice(1);
}

interface InspectionReportDocumentProps {
  report: InspectionReport;
  generatedAt: string;
  meta?: { propertyAddress?: string; tenantName?: string };
}

export function InspectionReportDocument({ report, generatedAt, meta }: InspectionReportDocumentProps) {
  const chargeableFindings = report.findings.filter((f) => !f.is_wear_and_tear && f.severity !== "none");
  const wearFindings = report.findings.filter((f) => f.is_wear_and_tear);
  const noIssueFindings = report.findings.filter((f) => f.severity === "none");

  return (
    <Document title="DepositDefender — Property Inspection Report">
      {/* Cover Page */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.coverTitle}>DepositDefender</Text>
        <Text style={styles.coverSubtitle}>Property Inspection Report</Text>
        <Text style={styles.coverMeta}>Generated: {generatedAt}</Text>
        <Text style={styles.coverMeta}>Jurisdiction: Ontario, Canada (RTA / LTB)</Text>
        {meta?.propertyAddress && (
          <Text style={styles.coverMeta}>Property: {meta.propertyAddress}</Text>
        )}
        {meta?.tenantName && (
          <Text style={styles.coverMeta}>Tenant: {meta.tenantName}</Text>
        )}

        <View style={[styles.summaryBox, { marginTop: 24 }]}>
          <View style={{ flexDirection: "row", justifyContent: "space-between", marginBottom: 10 }}>
            <Text style={{ fontSize: 12, fontFamily: "Helvetica-Bold" }}>Overall Condition</Text>
            <Text style={[{ fontSize: 12, fontFamily: "Helvetica-Bold" }, conditionStyle(report.overall_condition)]}>
              {conditionLabel(report.overall_condition)}
            </Text>
          </View>
          <Text style={styles.body}>{report.overall_summary}</Text>
          <View style={{ marginTop: 12 }}>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Total chargeable to tenant:</Text>
              <Text style={[styles.totalValue, { color: "#dc2626" }]}>
                {formatCAD(report.total_chargeable_cad)}
              </Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Normal wear &amp; tear (not chargeable):</Text>
              <Text style={styles.totalValue}>{formatCAD(report.total_wear_and_tear_cad)}</Text>
            </View>
            <View style={styles.totalRow}>
              <Text style={styles.totalLabel}>Findings:</Text>
              <Text style={styles.totalValue}>
                {chargeableFindings.length} chargeable · {wearFindings.length} wear &amp; tear · {noIssueFindings.length} no issue
              </Text>
            </View>
          </View>
        </View>

        <View style={styles.coverDisclaimer}>
          <Text>
            This report is generated by an AI system for documentation purposes only. Estimated costs are approximations based on Ontario market rates and should be verified with contractors. This is not legal advice. Contact the LTB at 1-888-332-3234 for guidance on allowable deductions.
          </Text>
        </View>

        <Text style={styles.footer}>
          DepositDefender — AI-assisted inspection report — LTB: 1-888-332-3234
        </Text>
      </Page>

      {/* Findings Pages */}
      {chargeableFindings.length > 0 && (
        <Page size="LETTER" style={styles.page}>
          <Text style={styles.sectionHeader}>
            Chargeable Damage ({chargeableFindings.length} finding{chargeableFindings.length !== 1 ? "s" : ""})
          </Text>
          <Text style={{ fontSize: 9, color: "#666", marginBottom: 12 }}>
            These items appear to be damage beyond normal wear and tear, potentially chargeable to the tenant.
          </Text>

          {chargeableFindings.map((finding, i) => (
            <View key={i} style={[styles.claimBox, { borderLeftColor: "#dc2626" }]} wrap={false}>
              <Text style={styles.claimTitle}>{finding.item}</Text>
              <Text style={{ fontSize: 9, color: "#666", marginBottom: 6 }}>{finding.location}</Text>

              <View style={{ flexDirection: "row", gap: 6, marginBottom: 8 }}>
                <Text style={severityBadgeStyle(finding.severity)}>
                  {severityLabel(finding.severity)}
                </Text>
                <Text style={[styles.verdictBadge, inspectionStyles.chargeableBadge]}>
                  CHARGEABLE
                </Text>
              </View>

              <View style={{ flexDirection: "row", marginBottom: 8 }}>
                <View>
                  <Text style={styles.label}>Estimated Repair Cost</Text>
                  <Text style={[styles.amountValue, { color: "#dc2626" }]}>
                    {formatCAD(finding.estimated_repair_cost_cad)}
                  </Text>
                </View>
              </View>

              <Text style={styles.label}>Description</Text>
              <Text style={styles.body}>{finding.description}</Text>

              <Text style={styles.label}>Repair Recommendation</Text>
              <Text style={styles.body}>{finding.repair_recommendation}</Text>

              {finding.photo_references.length > 0 && (
                <>
                  <Text style={styles.label}>Photo Evidence</Text>
                  {finding.photo_references.map((ref, j) => (
                    <Text key={j} style={styles.photoRef}>• {ref}</Text>
                  ))}
                </>
              )}
            </View>
          ))}

          <Text style={styles.footer}>
            DepositDefender — AI-assisted inspection report — LTB: 1-888-332-3234
          </Text>
        </Page>
      )}

      {wearFindings.length > 0 && (
        <Page size="LETTER" style={styles.page}>
          <Text style={styles.sectionHeader}>
            Normal Wear &amp; Tear ({wearFindings.length} finding{wearFindings.length !== 1 ? "s" : ""})
          </Text>
          <Text style={{ fontSize: 9, color: "#666", marginBottom: 12 }}>
            These items are considered normal wear and tear under the RTA and are NOT chargeable to the tenant.
          </Text>

          {wearFindings.map((finding, i) => (
            <View key={i} style={[styles.claimBox, { borderLeftColor: "#16a34a" }]} wrap={false}>
              <Text style={styles.claimTitle}>{finding.item}</Text>
              <Text style={{ fontSize: 9, color: "#666", marginBottom: 6 }}>{finding.location}</Text>

              <View style={{ flexDirection: "row", gap: 6, marginBottom: 8 }}>
                <Text style={severityBadgeStyle(finding.severity)}>
                  {severityLabel(finding.severity)}
                </Text>
                <Text style={[styles.verdictBadge, inspectionStyles.wearBadge]}>
                  WEAR &amp; TEAR — NOT CHARGEABLE
                </Text>
              </View>

              <Text style={styles.label}>Description</Text>
              <Text style={styles.body}>{finding.description}</Text>

              {finding.photo_references.length > 0 && (
                <>
                  <Text style={styles.label}>Photo Evidence</Text>
                  {finding.photo_references.map((ref, j) => (
                    <Text key={j} style={styles.photoRef}>• {ref}</Text>
                  ))}
                </>
              )}
            </View>
          ))}

          <Text style={styles.footer}>
            DepositDefender — AI-assisted inspection report — LTB: 1-888-332-3234
          </Text>
        </Page>
      )}

      {/* Summary & Next Steps */}
      <Page size="LETTER" style={styles.page}>
        <Text style={styles.sectionHeader}>Recommended Next Steps</Text>

        {report.recommended_next_steps.map((step, i) => (
          <Text key={i} style={styles.nextStepItem}>
            {i + 1}. {step}
          </Text>
        ))}

        <View style={[styles.summaryBox, { marginTop: 24 }]}>
          <Text style={{ fontSize: 11, fontFamily: "Helvetica-Bold", marginBottom: 8 }}>
            Cost Summary
          </Text>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Chargeable damage (tenant responsibility):</Text>
            <Text style={[styles.totalValue, { color: "#dc2626" }]}>
              {formatCAD(report.total_chargeable_cad)}
            </Text>
          </View>
          <View style={styles.totalRow}>
            <Text style={styles.totalLabel}>Normal wear &amp; tear (not chargeable):</Text>
            <Text style={styles.totalValue}>{formatCAD(report.total_wear_and_tear_cad)}</Text>
          </View>
        </View>

        <View style={[styles.coverDisclaimer, { marginTop: 24 }]}>
          <Text>
            This report is generated by an AI system. Estimated costs are approximations and should be verified with licensed contractors. This is not legal advice. Contact the Landlord and Tenant Board at 1-888-332-3234 for guidance.
          </Text>
        </View>

        <Text style={styles.footer}>
          DepositDefender — AI-assisted inspection report — LTB: 1-888-332-3234
        </Text>
      </Page>
    </Document>
  );
}
